# 箱码匹配规则 优先级从上至下
[Box]
IndexPosition = [] # 摄像头识别返回后的索引位置 根据默认规则, 第一位为条码，之后为二维码  Box的位置指定 同时需要指定Label的位置
StartWith = "" # 开头匹配的字符串
EndWith = "" # 结尾匹配的字符串
Contain = "" # 字符串包含的字符

# 标签码匹配规则 优先级从上至下
[Label]
IndexPosition = [] # 摄像头识别返回的索引位置 非特殊情况不建议修改  Label的位置指定 同时需要指定Box的位置  0,1,2,3,4,5,6,7,8,9
StartWith = "" # 开头匹配的字符串
EndWith = "" # 结尾匹配的字符串
Contain = "" # 字符串包含的字符